### ISSUE TITLE
AM 4 and Palomar 1

### ISSUE THREAD

**Issue by kadrlica** [apace7/local_volume_database#6]
AM 4 and Palomar 1 are low-luminosity outliers in the size-luminosity plane with respect to other classical globular clusters from the (updated) Harris catalog. In the LVDB they have M_V = -0.963 (AM 4) and M_V = -1.751 (Pal 1). However there are other references that have higher values of M_V for these systems. [Carraro 2009](https://arxiv.org/pdf/0901.2673) has M_V = -1.82 for AM2 and [Niederste-Ostholt et al. 2010](https://arxiv.org/pdf/1007.2806) has M_V = -2.5 for Palomar 1. I'm not sure if these are more believable than the (updated) Harris values, but it might be worth digging into.

![image](https://github.com/apace7/local_volume_database/assets/5605123/04243e5e-7fd3-4d74-a8dd-04a067e162f8)

**Comment by apace7** [comment]
The current M_V are computed from [Baumgardt 2018](https://ui.adsabs.harvard.edu/abs/2020PASA...37...46B/abstract).  Since this paper did not include distances, there was some convoluted process involving quoted M/L ratios to convert to M_V (although V should be distance independent). I believe there was some discussion with Baumgardt, Ting, and her students at the time. 

For AM 4, in addition to the paper quoted above, there is another HST analysis [Hamren 2013](https://ui.adsabs.harvard.edu/abs/2013AJ....146..116H/abstract) which has an almost identical M_V =-1.81. The Baumgardt paper gives V ~ 16.5 whereas this paper has V ~ 15.5. 

For Pal 1, there is another (older) study [Rosenburg 1998](https://ui.adsabs.harvard.edu/abs/1998AJ....115..648R/abstract) which has a similar M_V ~ -2.5. Just comparing the CMDs it is clear that Pal 1 is more massive than AM4 (Pal 1 has more of a RGB). Similar to AM4, Baumgardt has V ~  13.95 and the other Pal1 paper suggest V ~ 12.71. 

I am going to update Pal1 and AM4 with the brighter values (note that there will be some other differences due to updated Gaia distances).
In general, I haven't analyzed the Harris et al cluster literature as much as other objects and the values may be out of date.

**Comment by kadrlica** [comment]
Thanks Andrew! I know that the literature is a tangled mess, and I expect that we'll probably want to revisit/reanalyze some of the faint Harris systems as we try to understand the UFSCs.

**Comment by apace7** [comment]
updated in this commit: 
https://github.com/apace7/local_volume_database/commit/0f06b742e2afa6dd85cc4439ff6675402541e2a9
